ci: Run lint action on all target operating systems
Sentry CLI contains platform-dependent code. Therefore, to ensure we catch all linter errors, we need to run `cargo clippy` against all targets.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,9 +13,14 @@ env:
   RUSTFLAGS: -Dwarnings
 
 jobs:
-  lint:
-    name: Lint
-    runs-on: ubuntu-24.04
+  lint-each-os:
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-24.04, macos-14, windows-2022]
+
+    name: Lint (${{ matrix.os }})
+    runs-on: ${{ matrix.os }}
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
 
@@ -29,6 +34,18 @@ jobs:
 
       - name: Run Clippy
         run: cargo clippy --workspace --tests
+
+  lint:
+    needs: lint-each-os
+    runs-on: ubuntu-24.04
+    if: always() # Run even if lint-each-os fails
+    name: Lint
+    steps:
+      - name: Check for lint failures
+        if: contains(needs.lint-each-os.result, 'failure') || contains(needs.lint-each-os.result, 'skipped')
+        run: |
+          echo "Required lint check failed. You need to fix the problem before merging."
+          exit 1
 
   test:
     strategy:
